// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VäderdataCodeFirst.Data;

namespace VäderdataCodeFirst.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20210128171412_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("VäderdataCodeFirst.Models.WeatherInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Luftfuktighet")
                        .HasColumnType("int");

                    b.Property<string>("Plats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("WeatherInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
